import type { Metadata } from "next";
import { Onest, Permanent_Marker } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest"
});
const permanent_marker = Permanent_Marker({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-permanent-maker"
});

export const metadata: Metadata = {
  title: "Conoce la 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${permanent_marker.variable} ${onest.variable}`}>
        <Header />
        <div className="children">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
